webhook_url: https://hooks.slack.com/services/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

endpoints:
  - name: Portfolio
    url: https://me.seponik.dev
    timeout: 5s
    interval: 1h

  - name: Example API
    url: https://api.example.com/health
    timeout: 5s
    interval: 30m
    expected_status: 200
    
  - name: Example Website
    url: https://www.example.com
    timeout: 10s
    interval: 1h
    expected_status: 200